# The initial version of this file is copied from egs2/librimix/diar1/conf/train_diar_eda.yaml
# This config file is for EEND-EDA adaptation stage (training on data with 3 or 5 speakers).
# The training time is less than 10 minutes on a single V100-32GB GPU. 
# For the details about EEND-EDA, refer to the following papers:
# EEND-EDA: https://arxiv.org/pdf/2005.09921.pdf, https://arxiv.org/pdf/2106.10654.pdf

input_size: 322 # 23 * 15 - 23, - 23 because the tasks/diar will add 23 back

# network architecture
model_conf:
    diar_weight: 1.0
    attractor_weight: 1.0
    context_size: 7 # 7 frames are concatenated on each frame
    subsampling: 10 # subsample the input features by 10

frontend: default
frontend_conf:
    fs: 8k
    n_fft: 200 # 25ms
    win_length: 200 # 25ms
    hop_length: 80 # 10ms
    n_mels: 23

# encoder related
encoder: transformer
encoder_conf:
    input_layer: "linear"
    num_blocks: 4
    linear_units: 512
    dropout_rate: 0.1
    output_size: 256  # dimension of attention
    attention_heads: 4
    attention_dropout_rate: 0.1

# attractor related
attractor: rnn
attractor_conf:
    unit: 256 # same as encoder output size
    layer: 1
    dropout: 0.1
    attractor_grad: True

# optimization related
optim: adam
# accum_grad: 10
grad_clip: 5
max_epoch: 20
optim_conf:
    lr: 0.00001

# minibatch related
batch_type: unsorted
batch_size: 64
valid_batch_type: unsorted
valid_batch_size: 64
patience: none

# others:
best_model_criterion:
-  - valid
   - acc
   - max
keep_nbest_models: 10

# initialization method for model parameters
init: xavier_uniform

specaug: specaug
specaug_conf:
    apply_time_warp: false
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 30
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_range:
    - 0
    - 40
    num_time_mask: 2
