encoder: e_branchformer
encoder_conf:
    output_size: 1024
    attention_heads: 16
    attention_layer_type: selfattn
    pos_enc_layer_type: abs_pos
    rel_pos_type: latest #attention_qk_norm: false    # qk norm
    use_flash_attn: true    # flash attn
    cgmlp_linear_units: 4096
    cgmlp_conv_kernel: 31
    use_linear_after_conv: false
    gate_activation: identity
    num_blocks: 18
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d
    layer_drop_rate: 0.0
    linear_units: 4096
    positionwise_layer_type: linear
    use_ffn: true
    macaron_ffn: true
    merge_conv_kernel: 31

                
decoder: transformer
decoder_conf:
    attention_heads: 16
    linear_units: 4096
    num_blocks: 18
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.1
    src_attention_dropout_rate: 0.1 #self_attention_qk_norm: false   # qk norm  #src_attention_qk_norm: false    # qk norm #self_attention_use_flash_attn: true #src_attention_use_flash_attn: true

model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    length_normalized_loss: false
    sym_na: "<na>"

frontend_conf:
    n_fft: 512
    win_length: 400
    hop_length: 160

seed: 2022
log_interval: 400
num_workers: 4
batch_type: numel    #batch_size: 4
batch_bins: 10000000
accum_grad: 64
grad_clip: 1.0
max_epoch: 20
patience: none
init: none
best_model_criterion:
-   - valid
    - cer
    - min
keep_nbest_models: 4

use_amp: true
unused_parameters: true  #num_iters_per_epoch: 1000

optim: adamw
optim_conf:
    lr: 0.003
    weight_decay: 0.000001
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 6000

normalize: global_mvn
normalize_conf:
    stats_file: exp/s2t_stats_raw_en_bpe50000/train/feats_stats.npz

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 27
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_ratio_range:
    - 0.
    - 0.05
    num_time_mask: 5

init_param:
        - /work/hdd/bbjs/clin10/bootcamp/espnet/owsm_v3.1/valid.total_count.ave_5best.till45epoch.pth
ignore_init_mismatch: false