preprocessor: s2t_ctc
preprocessor_conf:
    na_symbol: "<na>"
    speech_length: 30
    speech_init_silence: 30
    text_prev_apply_prob: 0.5
    lang_apply_prob: 0.5
    nolang_symbol: "<nolang>"

frontend_conf:
    n_fft: 512
    win_length: 400
    hop_length: 160

normalize: global_mvn
normalize_conf:
    stats_file: exp/s2t_stats_raw_en_bpe50000/train/feats_stats_ctc.npz

specaug: specaug
specaug_conf:
    apply_time_warp: false
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 27
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_ratio_range:
    - 0.
    - 0.05
    num_time_mask: 10

encoder: e_branchformer_ctc
encoder_conf:
    output_size: 1024
    attention_heads: 16
    attention_layer_type: selfattn
    pos_enc_layer_type: abs_pos
    rel_pos_type: latest
    cgmlp_linear_units: 4096
    cgmlp_conv_kernel: 31
    use_linear_after_conv: false
    gate_activation: identity
    num_blocks: 27
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d8
    layer_drop_rate: 0.0
    linear_units: 4096
    positionwise_layer_type: linear
    use_ffn: true
    macaron_ffn: true
    merge_conv_kernel: 31
    interctc_layer_idx: [6, 12, 15, 21]
    interctc_use_conditioning: true
    use_cross_attention: [0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,]
    use_flash_attn: true    # flash attn

promptencoder: transformer
promptencoder_conf:
    output_size: 512
    attention_heads: 8
    linear_units: 2048
    num_blocks: 4
    use_flash_attn: true

model: espnet_ctc
model_conf:
    interctc_weight: 0.8
    sym_na: "<na>"
    ctc_asr_only: [true, true, true, false, false]

seed: 2022
log_interval: 400
num_workers: 4
batch_type: numel    #batch_size: 4
batch_bins: 10000000
accum_grad: 64
grad_clip: 1.0
max_epoch: 20
patience: none
init: none
best_model_criterion:
-   - valid
    - cer_ctc
    - min
keep_nbest_models: 4

use_amp: true
unused_parameters: true  #num_iters_per_epoch: 1000

optim: adamw
optim_conf:
    lr: 0.0001
    weight_decay: 0.000001
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 6000

init_param:
        - /work/hdd/bbjs/clin10/bootcamp/espnet/owsm_ctc/valid.total_count.ave_5best.till45epoch.pth
ignore_init_mismatch: false